import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import Head from 'next/head';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Lowy Institute',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
        <title>Hey Lowy Institute!</title>
        <link
          rel='stylesheet'
          href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'
          integrity='sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY='
          crossOrigin=''
          key='leaflet'
        />
      </Head>
      {/* <Script src='path/to/chartjs/dist/chart.umd.js' /> */}
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
